# Generated by Django 4.0.4 on 2022-05-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinicName', models.CharField(max_length=100)),
                ('clinicLogo', models.ImageField(upload_to='workshop/logo/')),
                ('physicianName', models.CharField(max_length=100)),
                ('physicianContact', models.CharField(max_length=100)),
                ('pfname', models.CharField(max_length=100)),
                ('plname', models.CharField(max_length=100)),
                ('pdob', models.CharField(max_length=100)),
                ('pcontact', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=500)),
                ('consultation', models.CharField(max_length=500)),
            ],
        ),
    ]
